version: 2

jobs:
  build:
    docker:
      - image: swift:4.2

    working_directory: /Users/distiller/project/
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test